version: "3.8"

services:

  service_a:
    build:
      context: .
      dockerfile: service_a/Dockerfile
    container_name: service_a

    environment:
      BOOTSTRAP_SERVER: kafka:9092
      TOPIC_INTEL: intel
      TOPIC_INTEL_SIGNALS_DLQ: intel_signals_dlq
      DB_NAME: target_bank
      COLL_NAME: targets
    depends_on:
      kafka:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy


  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: 'true'

      CLUSTER_ID: '1L6g7nGhU-eAKfL--X25wo'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - kafka_kraft:/var/lib/kafka/data


  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:9.3.0
      container_name: elasticsearch
      environment:
        - node.name=elasticsearch
        - discovery.type=single_node
        - xpack.security.enabled=false
        - bootstrap.memory_lock=true
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - esdata:/usr/share/elasticsearch/data
      ports:
        - "9200:9200"
      healthcheck:
        test:
          [
            "CMD-SHELL","curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
          ]
        interval: 10s
        timeout: 10s
        retries: 120

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

volumes:
  kafka_kraft:
  esdata:
    driver: local
